development:
  adapter: postgresql
  encoding: utf8
  database: foodoof
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: foodoof
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: foodoof
  pool: 5
  timeout: 5000
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>